### ISSUE TITLE
Finalize the implementation of the Sonatype strategy by implementing API payload and rate limits

### ISSUE THREAD

**Issue by antoine-coulon** [NodeSecure/vulnera#32]
For now, the strategy around Sonatype is not taking into account rate and payload limits imposed by the API.

- ### Payload limit 
When requesting multiple `components`, there is a payload limit of 128 components per requests). Given that a project might contains thousands of dependencies, we must provide a way to batch requests respecting taking care of that limit.

**Issue:**
For now, all the dependencies found from the scanner are provided [in the body of the request here ](https://github.com/NodeSecure/vuln/blob/8bc814349b3fe9615373ee0f7e14537de9752cc6/src/strategies/sonatype.js#L54). This is problematic because when dealing with a lot of dependencies, there is at the moment only one http request fired with all the dependencies, whereas we should batch X requests which each containing a maximum of 128 dependencies by payload. When providing more than 128 components per request, the API responds with an error. 

**Goal:**
Take for instance an array of [package urls](https://github.com/package-url/purl-spec) with 130 `components` (130 dependencies formatted as package urls). The goal is the create from this array `chunks` of size **128** and to fire an HTTP request to the API with each chunk.
In this example we would have:
- 1 HTTP request with components from 1 to 128
- 1 HTTP request with components from 128 to 130

- ### API rate limit

Probably needs an implementation using `@myunisoft/httpie`.

**Issue:**
Nothing specific with `vuln` here, but the interactions with the Sonatype API should handle _rate limit_ through the use of the `@myunisoft/httpie` http client. Without throttling requests, we are sure to exceed the rate limit of the API. 

**Goal:**
Use `@myunisoft/httpie` to configure _rate limit_, [there is an example here](https://github.com/MyUnisoft/httpie/blob/master/examples/ratelimit.mjs)

**Comment by AntonioliBenjamin** [comment]
Hi @antoine-coulon, i can try it ! :)

**Comment by antoine-coulon** [comment]
Hey @AntonioliBenjamin, 

I linked an example in the issue showing how we could integrate '@myunisoft/httpie' with a rate limit lib (it could be any lib that can be used with it). Feel free to pick any other rate limit that could work the same way

**Comment by AntonioliBenjamin** [comment]
Yes i saw the exemple but i have no idea how to set it.

const limit = pRateLimit({ 
   interval: 1_000, 
   rate: 10, 
   concurrency: 2 
 });

**Comment by antoine-coulon** [comment]
My bad I think I got it, do you mean the configuration of the rate limit? From what I can remember Sonatype's API doesn't mention the  threshold from which a client gets rate limited (https://community.sonatype.com/t/what-is-rate-limit-for-oss-index-rest-api/3752/2).

The easiest thing would be to test it through integration tests and play with different configurations to check by ourselves the limit. I could help you with that
