### ISSUE TITLE
Update documentation to deprecate Node.js Security WG DB

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/vulnera#46]
The Node.js Ecosystem Security Database is no more maintained (**it's deprecated**). So there is no reason to use it anymore for a production application. We should tag as deprecated in README (and also in the strategy markdown page).

![image](https://user-images.githubusercontent.com/4438263/180189492-6db22347-e12a-4257-a7d6-2f3eb9cd269d.png)

- Throw a deprecation warning when we use this strategy (see [process.emitWarning](https://nodejs.org/api/process.html#processemitwarningwarning-options))

https://github.com/NodeSecure/vulnera/blob/51bb814087da39e105f37a1538c43ca7b430b09b/src/strategies/index.js#L15-L16

Here a link to an official Node.js article that explain why: https://nodejs.medium.com/node-js-ecosystem-vulnerability-reporting-program-winding-down-591d9a8cd2c7

**Comment by PierreDemailly** [comment]
I'm on it

**Comment by fraxken** [comment]
@all-contributors please add @PierreDemailly for code, doc
